### ISSUE TITLE
Add "Remove metadata" option

### ISSUE THREAD

**Issue by MaraScott** [Gerkinfeltser/image-metadata-display#2]
Hi,

would it be possible to have an option to remove the metadata from the image or at least the workflow in it ?
and as well could it be possible to do so with a multi select ?

**Comment by Gerkinfeltser** [comment]
Hi @MaraScott,

Thanks for raising this issue! I totally understand the need to strip metadata from images efficiently, but unfortunately, I believe this request might be out of the scope for this VS Code extension. The purpose of this extension is primarily to display image metadata, and adding functionality to modify or strip that metadata could introduce unintended risks, such as accidental data loss.

If you're looking for a reliable way to strip metadata from images, I'd recommend using tools like **ExifTool** or **ImageMagick**, both of which are well-established for handling these types of tasks. You can use the following commands:

- **ExifTool**:  
   Strip metadata from a directory:  
   ```bash
   exiftool -all= -overwrite_original 'c:\path\to\your\folder'
   ```
   Strip metadata from a single image:  
   ```bash
   exiftool -all= -overwrite_original 'c:\path\to\image.png'
   ```

- **ImageMagick**:  
   Strip metadata from all PNGs in a folder:  
   ```bash
   magick mogrify -strip 'c:\path\to\your\folder\*.png'
   ```
   Strip metadata from a single image:  
   ```bash
   magick mogrify -strip 'c:\path\to\image.png'
   ```

I hope this helps, and please let me know if you need further assistance with anything else within the scope of this extension!

**Comment by MaraScott** [comment]
thx for your advise
